opt_in_rules:
    - closure_end_indentation
    - extension_access_modifier
    - closure_spacing
    - contains_over_first_not_nil
    - discouraged_object_literal
    - discouraged_optional_boolean
    - attributes
    - empty_count
    - fatal_error_message
    - first_where
    - force_unwrapping
    - implicit_return
    - implicitly_unwrapped_optional
    - joined_default_parameter
    - let_var_whitespace
    - literal_expression_end_indentation
    - prohibited_super_call
    - number_separator
    - operator_usage_whitespace
    - overridden_super_call
    - private_action
    - private_outlet
    - pattern_matching_keywords
    - redundant_nil_coalescing
    - sorted_first_last
    - sorted_imports
    - switch_case_on_newline
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - override_in_extension
    - multiline_arguments
    - multiline_parameters
    - single_test_class
    - yoda_condition

disabled_rules:
    - identifier_name
    - line_length
    - conditional_returns_on_newline
    - xctfail_message

excluded:
    - Example
    - Carthage
